### ISSUE TITLE
web-demo getting 8005 error (User not login error)

### ISSUE THREAD

**Issue by sailor95** [Particle-Network/particle-web-demo#10]
- Issue: Keep showing "User not login" error toast while try to make contract call, check in log it's 8005 error
- Environment: `localhost:3000` (by running yarn `start:web-demo`)
- Side notes
  - I can do the same contract call with same parameters on the official site https://web-demo.particle.network/ using the same account
  - I've setup .env file properly from Particle dashboard data

https://github.com/Particle-Network/particle-web-demo/assets/26215730/b7548b14-4a15-4b4e-8512-fa00581cb4f7

**Comment by davehuang-tw** [comment]
This issue was resolved after pulling the latest code from master and upgrading `@particle-network/auth` from `1.1.0` to `1.2.1`.
