### ISSUE TITLE
Can't switch chain

### ISSUE THREAD

**Issue by script-money** [Particle-Network/particle-web-demo#5]
Click any network and click "switch network" in metamask, will should error below, and switch chain fail.
<img width="1010" alt="Screenshot 2023-04-11 at 20 49 45" src="https://user-images.githubusercontent.com/74860630/231167563-fb448703-2cb1-4c69-8fca-aa640c27454f.png">

**Comment by chaichuanfa** [comment]
Refer to [MetaMask error](https://github.com/MetaMask/metamask-extension/issues/18509).

We will track this issue until it is resolved.
