### ISSUE TITLE
demo vue doesn't work

### ISSUE THREAD

**Issue by MaxVast** [Particle-Network/particle-web-demo#7]
Hello,

I've cloned the vuejs demo part but it doesn't work for me, I get this error 'socket.ts:19 Uncaught ReferenceError: global is not defined at socket.ts:19:12'
Did I forget something?
Can you help me?
Your solution was recommended to me for the creation of my dapp and I'm very interested in using particle.network.

**Comment by chaichuanfa** [comment]
1. add .env to `vue-vite-starter`
2. get project config from [Dashboard](https://dashboard.particle.network/)
3. read [Docs](https://docs.particle.network/developers/connect-service/sdks/web#connect-core)

**Comment by MaxVast** [comment]
Hi
Thank you for your reply.
